compiler-plugin/src/main/kotlin/arrow/meta/plugins/typeclasses/TypeClassesPlugin.kt, gradle/wrapper/gradle-wrapper.properties, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/IdeMetaPlugin.kt, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/plugins/typeclasses/TypeclassesIdePlugin.kt
moves TC syntheticResolution to idea-plugin
=> ide refactoring

compiler-plugin/src/main/kotlin/arrow/meta/internal/Noop.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/optics/LensPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Scope.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/ScopedList.kt, idea-plugin/src/main/kotlin/arrow/meta/dsl/ide/editor/lineMarker/LineMarkerSyntax.kt, idea-plugin/src/main/kotlin/arrow/meta/dsl/ide/utils/IdeUtils.kt, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/plugins/comprehensions/comprehensionsIdePlugin.kt, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/plugins/higherkinds/HigherKindsIdePlugin.kt, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/plugins/nothing/NothingIdePlugin.kt, idea-plugin/src/main/kotlin/arrow/meta/plugin/idea/plugins/optics/OpticsIdePlugin.kt
=> Poly line marker for polymorphic functions with type class constrains

.github/workflows/build.yml
=> Configuration: avoid duplicated checks for all kind of branches

.github/workflows/publish_website.yml
@franciscodr will help with the pending tasks
=> Publish documentation

testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt, testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/ExampleTest.kt
* Add variables evaluation
* Improve message in case of error
=> Testing: allow variables evaluation

.github/workflows/publish_artifacts.yml
Note: I've removed the previous artifact from OSS.
=> CI: it's not necessary a new artifact name

compiler-plugin/src/main/kotlin/arrow/meta/quotes/BinaryExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/BinaryOper.kt
See #89 for referencing, meant to be a place for discussion about AST elements with Scope templating
=> `binaryOper` Quote and Template Scope

.github/workflows/publish_artifacts.yml, compiler-plugin/build.gradle, gradle/gradle-mvn-push.gradle, gradle/upload-shadow.gradle, idea-plugin/build.gradle, testing-plugin/build.gradle
It includes:
* `gradle/gradle-mvn-push.gradle`
I'll remove it as soon as the problem with `raw.githubusercontent.com` in Spain is solved.
=> CI: just one task for upload artifacts

README.md, compiler-plugin/src/main/kotlin/arrow/meta/Meta.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/helloWorld/DummyPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/typeclasses/TypeClassesPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/NamedFunction.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/higherkinds/HigherKindsIdePlugin.kt
=> Updated func -> namedFunction 

docs/README.md
* Add website system prerequisites info
=> Add website system prerequisites info

compiler-plugin/src/main/kotlin/arrow/meta/quotes/KtLambdaExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/LambdaExpression.kt
=> Lambda Expression Quote and Template Scope

compiler-plugin/src/main/kotlin/arrow/meta/quotes/BinaryExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/ForExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/LambdaExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/NamedFunction.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Parameter.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Property.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/PropertyAccesor.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/TypeAlias.kt, docs/build.gradle
Added paramater documentation for all available meta extensions, made sure the current parameter names in scopes have been updated.
=> AST Element scope & template minor doc cleanups

README.md
Small changes in `README.md` about section levels.
=> documentation: small format issues

compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/BinaryExpression.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/TypeReference.kt
No documentation added for now but will open an issue for folks to contribute.
=> Type element quote and template scope

compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/ValueArgument.kt
=> Value argument quote and template scope

compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/ImportDirective.kt
=> Import directive quote and template scope

compiler-plugin/build.gradle, docs/build.gradle, testing-plugin/build.gradle, testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- Dependence of regular compiler-plugin
- Extract dependencies to have a single version of Kotlin
=> config: fix dependencies

compiler-plugin/src/main/kotlin/arrow/meta/quotes/File.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/LambdaExpression.kt
=> File quote and template scope

compiler-plugin/src/main/kotlin/arrow/meta/internal/registry/InternalRegistry.kt
Fix to the first of errors with 1.3.60 which is also compatible with 1.3.50.
=> Small fix to 1.3.60 version

testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/TransformReplaceTest.kt, testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/MetaPlugin.kt, testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/transform/TransformReplacePlugin.kt
This PR provides tests to Transform replace. This is related to https://github.com/arrow-kt/arrow-meta/issues/219
=> Transform replace tests

docs/index.md
@raulraja We might want to add a brief text before the video
=> Adding Raul and Simon Lambda World talk to main doc page

compiler-plugin/src/main/kotlin/arrow/meta/plugins/helloWorld/DummyPlugin.kt, docs/index.md
* Add Hello World information
* Change video as embedded for website (because it had a format for README page where it's not possible to include embedded videos)
=> Documentation

.github/workflows/publish_artifacts.yml
This kind of things happens... I received an answer right now. Everything is working as expected and the last version is right :+1:
=> Undo temporary change: enable Gradle plugin publication

.github/workflows/build_documentation.yml, .github/workflows/publish_documentation.yml, scripts/build-and-run-website.sh
@i-walker, the target of this pull request is `is-more-docs` branch.
=> CI: join commands to manage dependencies

docs/_sass/components/_doc-content.scss
This PR solves #283 adding line break before the first `code` element in every table row.
=> Separate description and definition in tables

docs/_data/sidebar.yml
=> Broken link

compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/ForExpressionTest.kt
#340 ForExpressionTest file refactor and new tests.
=> #340 ForExpression Quote and Template System validation

.github/workflows/kotlin-sync.yml
The sync bot:
- it creates an issue in case of failure with a new EAP version
- it create a pull request in case of success with a new EAP version
This pull request adds the version to pull request title for **change logs**.
It has been checked in another environment successfully.
=> Sync bot: add version in pull request title

.github/workflows/kotlin-sync.yml
Add a full description about the steps done by the bot to create automatic PRs.
It also replaces the GitHub Action to create the pull request.
=> Sync bot: add full description to PRs

compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/Node.kt, compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/psi/Converter.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/MetaExtensions.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/declaration/PropertyAccessor.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/Property.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/PropertyAccessorPlugin.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/PropertyPlugin.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/PropertyAccessorTest.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/PropertyTest.kt
=> Property and PropertyAccessor quote and template validation

compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/Property.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/pbt/QuoteTest.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/PropertyTest.kt
=> Property test scope properties added, QuoteTest included and documentation updated

compiler-plugin/src/main/kotlin/arrow/meta/quotes/declaration/PropertyAccessor.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/pbt/QuoteTest.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/PropertyAccessorTest.kt
=> tests added, QuoteTest included and documentation updated

idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/intention/IntentionSyntax.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/extensions/ExtensionProviderSyntax.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/internal/registry/IdeInternalRegistry.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/extension/ExtensionProvider.kt
Allow implementations in multiple Languages for FiletypeExtensions and LanguageExtension.
=> Allow multiple Languages in Meta

compiler-plugin/src/main/kotlin/arrow/meta/Meta.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/helloWorld/DummyPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/higherkind/HigherKindPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/optics/LensPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/SyntheticElement.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/Transform.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/classorobject/ClassDeclaration.kt, compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/Property.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformManyPlugin.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformNewSourcePlugin.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformReplacePlugin.kt, testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/HelloWorldPlugin.kt
In order to replace Scope<KTProperty> to Property in LensPlugin I performed these changes
=> synthetic renamed to syntheticScope and syntheticElement added for use Property inside LensPlugin

compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/LambdaExpression.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/pbt/QuoteTest.kt, compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/LambdaExpressionTest.kt
=> QuoteTest uncommented but ignored, lambdaExpression tests improvement and added to QuoteTest

gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt
If Arrow Meta Gradle plugin is applied from Intellij IDEA and Arrow Meta IDEA plugin isn't installed, it will happen:
Next tasks:
- It only considers SNAPSHOT versions. It will have to be updated when having a release version.
- The final step about restarting will be removed starting with Intellij IDEA 2020.1 release and having a [dynamic plugin ](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html) (for instance, components are used in Arrow Meta IDEA plugin and they must be migrated to services, extensions or listeners).
=> Install IDEA plugin from Gradle plugin

.github/workflows/publish_artifacts.yml, .github/workflows/templates/updatePlugins.xml, README.md, compiler-plugin/gradle.properties, compiler-plugin/src/main/kotlin/arrow/meta/plugins/helloWorld/DummyPlugin.kt, gradle-plugin/build.gradle, gradle-plugin/gradle.properties, gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt, idea-plugin/gradle.properties, testing-plugin/gradle.properties
From:
```
io.arrow-kt:arrow-meta-compiler-plugin:<version>
io.arrow-kt:arrow-meta-testing-plugin:<version>
io.arrow-kt:arrow-meta-gradle-plugin:<version>
io.arrow-kt:arrow-meta-idea-plugin:<version>
```
to:
```
io.arrow-kt:compiler-plugin:<version>
io.arrow-kt:testing-plugin:<version>
io.arrow-kt:gradle-plugin:<version>
io.arrow-kt:idea-plugin:<version>
```
=> Configuration: remove arrow-meta from artifact IDs

.github/workflows/sandbox/1.3.70-eap-23.diff
It solves #423 for tomorrow morning check.
=> Fix patch for 1.3.70

idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/IdeSyntax.kt
regarding #509 
Deprecated API until bug is fixed.
=> Disable IntentionSyntax

idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/action/AnActionSyntax.kt
for folding builder in type-proofs branch
=> Add EditorActions

.github/workflows/build_artifacts.yml
Until the problem with IR is fixed in `1.3.7x`.
=> Disable check for the next version

.github/workflows/kotlin-sync.yml
Until IR error is solved for 1.3.7x or 1.4x
=> Kotlin sync: just compilation check

.github/workflows/sandbox/1.3.70-eap.diff, idea-plugin/build.gradle
`org.celtric.kotlin:kotlin-html` includes a `meta` function that causes conflicts: https://github.com/arrow-kt/arrow-meta-examples/pull/24#issuecomment-626601226
=> Fix transitive dependencies for Arrow Meta IDEA Plugin

.github/workflows/publish_artifacts.yml, idea-plugin/build.gradle
Because JETBRAINS_TOKEN secret has been configured.
=> Solve #352. Publish IDEA Plugin release versions

idea-plugin/src/main/kotlin/arrow/meta/ide/IdeMetaPlugin.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/markers/coercionLineMarker.kt
disable quotes and IndexOutofBounce error
=> resolve errors

.github/workflows/intellij_plugin_verification.yml, idea-plugin/build.gradle
It provides a new Gradle task for running the Intellij Plugin Verifier
```
./gradlew runPluginVerifier
```
That task comes from https://github.com/FWDekker/intellij-randomness
- **Intellij Plugin Verification** check should create the same result as before.
=> Provide a Gradle task for running the Intellij Plugin Verifier

.github/workflows/sandbox/1.4-M3-eap.diff, compiler-plugin/src/main/kotlin/arrow/meta/phases/CompilerContext.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/Proofs.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/resolve/cache/ProofsCache.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/markers/ProofMarkers.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/psi/ProofsPsi.kt, idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/resolve/ProofsKotlinCacheService.kt, idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/proofs/repo/GradleTypeproofsTest.kt
This initial draft refactors the cache as a member of the compilerContext.
=> resolve multiple thread blocks in proof cache

compiler-plugin/src/test/kotlin/arrow/meta/plugins/refinement/RefinementTests.kt
Fixes #581 
[CoercionInspectionTest is being removed in another PR]
=> Enable back some refinement tests

.github/workflows/publish_artifacts.yml, build.gradle, gradle-plugin/build.gradle, gradle.properties, gradle/publication.gradle
Reverts arrow-kt/arrow-meta#735
=> Revert "Configuration: use of the new publication workflow"

build.gradle, gradle-plugin/build.gradle
The last improvements make this change possible,
=> Gradle Plugin: use local project

gradle/build-idea-plugin.gradle, idea-plugin/build.gradle
The libraries that are added to fix the errors that are raised by the Intellij Plugin Verifier impact on Arrow Meta IDE Plugin (errors about incompatibilities and missing classes)
=> IDE plugin: remove additional libraries

.github/workflows/publish_artifacts.yml
=> IDE Plugin: allow installation of specific versions

.github/workflows/publish_artifacts.yml, .github/workflows/templates/updatePlugins.xml
=> IDE Plugin: fix custom repository

.github/workflows/publish_artifacts.yml
The internal version of the SNAPSHOT zip should be the same as the included version in the custom repository.
=> IDE Plugin: fix internal version

.github/workflows/intellij_plugin_verification.yml
Remove duplicated env variable.
=> Clean configuration

compiler-plugin/src/main/kotlin/arrow/meta/dsl/codegen/ir/IrSyntax.kt, compiler-plugin/src/main/kotlin/arrow/meta/internal/registry/InternalRegistry.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/codegen/ir/IRGeneration.kt
In following PR's I will add more tests.
=> Quick fix for IrSyntax

build.gradle
A tiny change to avoid the last random failures when validating documentation.
=> Doc: fix last failures when validating

.github/workflows/build_documentation.yml, .github/workflows/publish_artifacts.yml, .github/workflows/publish_documentation.yml
- Fix the error when publishing because of merging into `master` branch
- Remove unnecessary steps
- Use of installed packages in GH environments
=> Configuration: update actions

compiler-plugin/src/main/kotlin/arrow/meta/MetaPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/phases/codegen/ir/IrUtils.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/ProofsPlugin.kt, compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/ir/ProofsIrCodegen.kt
Co-authored-by: Raúl Raja Martínez <raulraja@gmail.com>
=> Upgrade to 1.5.0-RC: improve proveReturn

build.gradle
=> Configuration: remove unused repository

gradle/publication-mpp.gradle
=> Fix publication

gradle-plugin-commons/src/main/kotlin/arrow/meta/plugin/gradle/ArrowMetaGradlePlugin.kt
=> Notify the applied plugin in the console output

arrow-refined-types/build.gradle, arrow-refined-types/src/jvmMain/kotlin/arrow/refinement/RefinedArrowExtension.kt, arrow-refined-types/src/jvmTest/kotlin/arrow/refinement/tests/RefinedArrowExtensionTests.kt
The goal is to be able to work with arrow type seamlessly
=> Add toEither toValidated to refined types

plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/SolverState.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/ir/ConstraintsAnnotations.kt, plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR handles `for`, `while`, and `do` loops. The general idea is the following: every time we find one looping construct, we begin two "branches",
1. On the one hand we check the body of the loop, which will hold whenever the condition is true. So we assert the condition, and then check the body. The only possible outside effect is if we return, so other than that we abort the execution.
2. Then we check whatever is after the loop, in which case we know that the condition is false. So we assert the negation of the condition, and ask the analysis to keep going.
You might be wondering: "mutable variables! in that case (1) is not really independent of (2)!" For this to be true we had to ensure that changing the value of a mutable variable does not change the analysis. And that holds, …
=> [Analysis] Loops

plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
Just a couple of expressions which were missing, but require just a few lines of code.
=> [Analysis] Annotated expressions and 'run' without receiver

plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Expressions.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/model/Return.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/model/ReturnPoints.kt, plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR adds support for exception handling. Note that the support itself is very _rough_, since we have no detailed information about which exceptions may be thrown, so we follow _every_ possibility. But it's sound.
=> [Analysis] Exceptions (try, catch, finally)

plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Declarations.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/EntryPoint.kt, plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Expressions.kt, plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR refactors and uses parts of the primary constructor check to check "enumeration entries."
=> [Analysis] Enumeration entries

plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This is an interesting example which shows that we can use this plug-in in the same way we could use the Refined one.
=> [Analysis] Extra example of invariant checking

docs/docs/analysis-quickstart.md, docs/docs/index.md, docs/docs/proofs-quickstart.md
- Fix broken links,
- Point to the Optics documentation.
=> Small updates to docs

.github/workflows/build_artifacts.yml, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/DeclarationUtils.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Declarations.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/EntryPoint.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FromDSL.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/errors/ErrorIds.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/errors/ErrorMessages.kt, plugins/analysis/java-plugin/src/main/kotlin/arrow/meta/plugins/analysis/java/ast/JavaResolutionContext.kt, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/KotlinResolutionContext.kt, plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
This was missing from Analysis, but turned out to be not so difficult after all.
=> [Analysis] Support implicit primary constructors

docs/docs/analysis-java.md, plugins/analysis/java-gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/AnalysisJavaGradlePlugin.kt
A `package` line was missing, which was making the plug-in fail when applied 😅
=> [Analysis] Fix for Java plug-in

docs/docs/_data/analysis/features.yml, docs/docs/_data/analysis/sidebar.yml, docs/docs/_data/meta/features.yml, docs/docs/analysis-wrappers.md, docs/docs/analysis/types/README.md, docs/docs/analysis/wrappers/README.md, plugins/analysis/example/src/commonMain/kotlin/arrow/analysis/BadExample.kt
This should only be merged after @franciscodr had merged the solution to the problem with docs publication.
=> [Analysis] Docs about wrappers

.github/workflows/build_artifacts.yml, .github/workflows/build_documentation.yml, .github/workflows/publish_artifacts.yml, .github/workflows/publish_documentation.yml
Fixes #965
@akulpillai, could you check that this indeed fixes the problem?
=> Update workflow action versions

gradle.properties, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/context/types/Type.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Declarations.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/EntryPoint.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FromDSL.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/errors/ErrorIds.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/search/ConstraintSearch.kt, plugins/analysis/java-plugin/src/main/kotlin/arrow/meta/plugins/analysis/java/AnalysisMessages.kt, plugins/analysis/java-plugin/src/main/kotlin/arrow/meta/plugins/analysis/java/ast/JavaResolutionContext.kt, plugins/analysis/kotlin-plugin/src/main/java/arrow/meta/plugins/analysis/errors/MetaDefaultErrorMessagesJvm.java, plugins/analysis/kotlin-plugin/src/main/java/arrow/meta/plugins/analysis/errors/MetaErrors.java, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/Phases.kt, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/KotlinResolutionContext.kt, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/ast/KotlinInterpreter.kt, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/elements/KotlinPropertyDelegate.kt, plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/elements/KotlinThrowExpression.kt, plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
Fixes #999 
Fixes #1000 
Fixes #1002 
Fixes #1003 
Closes #1004
=> [Analysis] Fix problems after 2.0 release

plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/DescriptorUtils.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ResolvedCallUtils.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/ExpressionToFormula.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FindDescriptor.kt, plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FromDSL.kt, plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt, plugins/analysis/laws/src/commonMain/kotlin/arrow/analysis/laws/kotlin/Collections.kt
=> [Analysis] Better support for vararg

plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/EntryPoint.kt, plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
=> [Analysis] Support expect/actual/external

plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/KotlinResolvedCall.kt
Fixes #1014
Some of these extensions methods change package from one version to another, leading to `NoSuchMethod` or `ClassNotFound` exceptions. In this case the solution is simply to inline the implementation.
=> Do not use 'getReceiverExpression' directly

plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/Primitive.kt
=> Do not use multiplication from rational theory

build.gradle.kts
Hope this one is the definitive one...
=> Fix publication workflow, again
