arrow-kt/arrow-meta

- build.gradle
Ports the build tasks from the old location and rewrites them to refer to the local module tasks.
> `buildMeta` & `publishAndRunIde` build tasks

- .github/workflows/publish_artifacts.yml
- build.gradle
- compiler-plugin/build.gradle
- compiler-plugin/gradle.properties
- docs/build.gradle
- docs/gradle.properties
- gradle-plugin/build.gradle
- gradle.properties
- idea-plugin/build.gradle
- idea-plugin/gradle.properties
- testing-plugin/build.gradle
- testing-plugin/gradle.properties
* Add **Github Actions** to publish artifacts:
* `io/arrow-kt/arrow-meta-testing-plugin`
* `io/arrow-kt/arrow-meta-idea-plugin`
* `io/arrow-kt/arrow-meta-compiler-plugin`
* `io/arrow-kt/arrow-meta-docs`
* **NOTE**. Old shell scripts are not used (`deploy-scripts`  directory). Just an additional command in Github Actions.
* Add Bintray configuration
* Use `gradle-mvn-push` to upload archives in the same way as Arrow
* Add `gradle.properties` for every artifact except for `gradle-plugin` because it has its own way to be published: #41 
* [Add secrets](https://help.github.com/en/github/automating-your-workflow-with-github-actions/virtual-environments-for-github-actions#creating-and-using-secrets-encrypted-variables): `BINTRAY_USER`, `BINTRAY_API_KEY`
> Configuration: publish artifacts

- build.gradle
- compiler-plugin/build.gradle
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/higherkind/HigherkindTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/lens/LensTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/typeclasses/TypeClassesTest.kt
- docs/build.gradle
- testing-plugin/build.gradle
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/ExampleTest.kt
* Remove the use of **arrow-annotations** from `rr-meta-prototype-integration` branch
* All the arrow dependencies have the same version from `gradle.properties` (`VERSION_NAME`)
* That version is provided to tests through a system property to define the tests configuration.
* Remove all the TODOs and comments related to the use of `rr-meta-prototype-integration` branch
> Dependencies: unify versions of arrow-annotations

- .github/workflows/build.yml
- gradle-plugin/build.gradle
After some checks, everything is ok with our Gradle plugin and I'm going to publish another version with the right groupId.
I also fixed the CI to avoid duplicated checks. If we follow these branch names:
- `fix/...`
- `feature/...`
- `doc/...`
- `release/...`
checks won't be executed twice.
> Fix configuration: CI and Gradle Plugin groupId

- compiler-plugin/src/main/kotlin/arrow/meta/quotes/Property.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/PropertyAccesor.kt
- testing-plugin/build.gradle
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationData.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/TestingLibraryWrapper.kt
The following PR includes a new `Quote` for `KtProperty` and `KtPropertyAccessor` with built-in template `Scope`.
Additionally, it replaces the testing interpreter to be stack safe and prepares the framework for the inclusion of custom ad-hoc Quote based plugins that can run on tests.
> Testing improvements + Property Quotes

- docs/_config.yml
This will make the final site to be generated to not serve these files/dirs, as they are not necessary.
> Exclude unnecessary files from Jekyll built site

- compiler-plugin/src/main/kotlin/arrow/meta/internal/registry/InternalRegistry.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/IdeMetaPlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/action/AnActionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/action/AnActionUtilitySyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionUtilitySyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/intention/IntentionExtensionProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/intention/IntentionExtensionProviderUtilitySyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/syntaxHighlighter/SyntaxHighlighterExtensionProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/extensions/ExtensionProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/utils/IdeUtils.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/internal/registry/IdeInternalRegistry.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/AnActionExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/ExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/IdeContext.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/IntentionExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/action/AnActionExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/extension/ExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/intention/IntentionExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/syntaxHighlighter/SyntaxHighlighterExtensionProvider.kt
We've been executing environmental changes to the editor without control prior to this. 
This PR tries to align the ide DSL to the behavior of ExtensionPhase and composes the necessary  SumTypes, which are then interpreted by the InternalRegistry. Removing the hack with `ideRegistry`
ExtensionProvider is an ADT for 2 reasons because we want users to manipulate the environment once at a time and we can control the execution more granular. The interpreter in the ide solely asks for a SumType of a specific shape and as we grow in our algebra of manipulating the editor environment. So does our ADT. 
These 3 groups of ExtensionPhases need to be addressed:
I am open for suggestions :)
> Separates Interpreter from the DSL

- .github/workflows/publish_artifacts.yml
- .github/workflows/publish_documentation.yml
- README.md
- docs/README.md
- docs/index.md
- scripts/build-and-run-website.sh
- scripts/commons.sh
- scripts/release-candidate-gradle-plugin.sh
- scripts/release.sh
Several improvements about documentation:
- Get the version from `gradle.properties` and create a folder for the website with that version to sync with S3 bucket. In this way, we can use the same S3 bucket for all the versions. I've checked it in a personal repository before. cc: @franciscodr 
- "Contributing" and "License" sections.
- Add badges at `README` and the website main page.
- Latest snapshot
- Latest Gradle Plugin version
- Publish artifacts status
- Publish documentation status
- Kotlin version
- License
- Script to build and run the website in a local environment and not to have to follow instructions in a document: `scripts/build-and-run-website.sh`
- Having scripts to create release branches:
- To publish release candidates for Gradle Plugin: …
> Documentation

- .github/workflows/publish_documentation.yml
I'm leaving it as a comment for now, but when we start publishing versioned sites of the docs we need to set a specific parameter `baseurl` when building the site.
This value will be the same as the directory where the site will be hosted/published, in our case the name/version of the release: `$MAYOR_MINOR_VERSION`
This will correctly set the paths on the menu entries, assets, and such.
> Set baseurl param when building the site 

- idea-plugin/build.gradle
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/dsl/synthetic/SyntheticResolutionTestSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/types/HeavyTestSyntax.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/typeclasses/TypeClassResolutionTest.kt
This is a pull request on `ja-heavy-testing`:
* To use `kotlin-compile-testing` in `idea-plugin`
* To avoid #63 
I think `idea-plugin` doesn't need to use `testing-plugin` but `kotlin-compile-testing`:
> Proposal on `ja-heavy-testing`

- .github/workflows/build_artifacts.yml
- .github/workflows/publish_artifacts.yml
- compiler-plugin/build.gradle
- docs/build.gradle
- docs/gradle.properties
- testing-plugin/build.gradle
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/ExampleTest.kt
- Update checks for the use of shadowJar
- `configuration: 'shadow'` for `compiler-plugin` dependencies
- Recover `compile` for `"org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"` to be included in shadowJar
- Update `metaDependencies`
- Remove doc artifact from publication in artifact repository
- Remove duplicated test in testing-plugin.
> Fix: use of shadowJar for compiler plugin

- idea-plugin/src/main/kotlin/arrow/meta/ide/IdeMetaPlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionUtilitySyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/dummy/DummyIdePlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/purity/PurityPlugin.kt
This aims to solve https://github.com/arrow-kt/arrow-meta/issues/28
The `InspectionSyntax` allows us to write costume Inspections based on Tooling, what Kotlin already uses in the editor. This allows plugin developers to not only indicate code elements, which need to be inspected but additionally to manipulate them programmatically. 
As here to add a `suspended` keyword to a function. 
`ApplicableInspections` can traverse any KtElement. Furthermore, we can extend the Scope of Inspection to the whole Project instead of individual files. This allows users to write fast fixes, which are universal for the whole project and deal with subsequent issues. 
I'll add checks for calls in the function body, which return Unit or Nothing.
We should also add Text for an explanation.
> Initial purity plugin

- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/nothing/NothingIdePlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/purity/PurityPlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/types/LightTestSyntax.kt
A general cleanUp for the editor fixes unnecessary NPE with `Inspections`, boosts performance for LineMarker Resolution and cleansUp `InspectionSyntax`.
> Inspection cleanUp

- .github/workflows/publish_artifacts.yml
Gradle Plugin versions appear without an order and latest version is wrong.
This pull request adds an incremental number and changes Gradle Plugin versions from:
`<version>-<short commit hash>`
to:
`<version>-<incremental number>-<short commit hash>`
Incremental number starts with 0.
> CI: add incremental number for ordered Gradle Plugin versions

- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/resolve/FragmentProviderComponent.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/resolve/MetaSyntheticPackageFragmentProvider.kt
Changes:
- Performance optimization by doing much less cache refreshes. The cache only needs to be refreshed after changes to .class files. We were refresh always, which is too often.
- refresh highlighting and warnings in all open editors after cache refresh. This should remove the warnings in almost all cases.
I made these changes while debugging the fragment provider for #96
> Small fixes to fragment provider refresh

- gradle.properties
*Arrow* 0.10.3 has been released and the last version of *Arrow* is `0.10.4-SNAPSHOT`
> CI: update Arrow version to 0.10.4-SNAPSHOT

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/WhenCondition.kt
This PR introduces `KtWhenCondition` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> When condition scope and quote

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/FinallySection.kt
This PR introduces `KtFinallySection` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Finally quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/BlockExpression.kt
This PR introduces `KtBlockExpression` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Block expression and quote

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/CatchClause.kt
This PR introduces `KtCatchClause` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Catch quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ThrowExpression.kt
This PR introduces `KtThrowExpression` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Throw expression quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/IsExpression.kt
This PR introduces `KtIsExpression` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Is expression quote and its scope mapping

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ReturnExpression.kt
This PR introduces `KtReturnExpression` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Return quote and its scope mapping

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/AnnotatedExpression.kt
This PR introduces `KtAnnotatedExpression` quote and its scope mapping. This PR is related to https://github.com/arrow-kt/arrow-meta/issues/89
> Create annotated expression quote and its scope mapping

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ParameterList.kt
This PR introduces `KtParameterList` quote and its scope mapping. This PR is related to #89
> Parameter list quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ModifierList.kt
This PR introduces `KtModifierList` quote and its scope mapping. This PR is related to #89
> Modifier list quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/quotes/Class.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/TypeAlias.kt
> Type reference quote and template scope

- testing-plugin/build.gradle
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilationData.kt
- testing-plugin/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/ExampleTest.kt
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/HelloWorldPlugin.kt
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/MetaPlugin.kt
**Note**: I didn't find a way to provide `Plugin` but `Meta` (the plugin is defined under `Meta` and I couldn't add a reference to the created plugin without being inside a class which extends `Meta`).
> testing-plugin: allow to test Meta plugins

- .github/workflows/kotlin-sync.yml
Add these features to an **issue** when there is a failure with the last Kotlin EAP version:
* Labels
* Assignees
* Link to the trace
> sync check: labels, assignees and link

- compiler-plugin/build.gradle
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/TransformRemoveTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/TransformReplaceTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformMetaPlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformRemovePlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformReplacePlugin.kt
- testing-plugin/src/test/kotlin/arrow/meta/plugin/testing/plugins/MetaPlugin.kt
Keep `testing-plugin` just with examples about how to write tests.
- Move tests about `Transform` quote from `testing-plugin` to `compiler-plugin`
- Add a new `TransformMetaPlugin` for it.
- Add a missing dependency in `compiler-plugin` to compile the new tests.
```
compiler-plugin/src/test/kotlin/arrow/meta/
├── plugins
│   ├── comprehensions
│   │   └── ComprehensionsTest.kt
│   ├── higherkind
│   │   └── HigherkindTest.kt
│   ├── lens
│   │   └── LensTest.kt
│   ├── typeclasses
│   │   └── TypeClassesTest.kt
│   └── union
│       └── UnionTest.kt
└── quotes
└── transform
├── plugins
│   ├── TransformMetaPlugin.kt
│   ├── TransformRemovePlugin.kt
│   └── TransformReplacePlugin.kt
├── TransformRemoveTest.kt
└── TransformReplaceTest.kt
```
Thanks @bloderxd again for these new tests!!
> Tests reorganization (Marie Kondo’s style :D)

- build.gradle
This is not related to #236 but I found this inconsistency which can cause problems.
> Fix repositories for Kotlin EAP versions

- .github/workflows/publish_artifacts.yml
Versions with more than one week cannot be deleted from Gradle Plugin Portal and our request to delete them hasn't been done.
This pull request disables the publication until old versions are deleted (we have a wrong latest version now and the new versions don't follow the right latest version).
> Temporary change: disable Gradle plugin publication

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ObjectDeclaration.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/ObjectDeclarationTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/ObjectDeclarationPlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/ScopeMetaPlugin.kt
This PR proposes the creation of tests to scopes starting with `ObjectDeclaration`, these tests could help on documentation building since we can get all scope property informations that we need.
> Create test to object declaration scope

- docs/_data/sidebar.yml
- docs/_includes/_sidebar.html
It updates the link of the Arrow Meta logo to point out to `https://meta.arrow-kt.io`. Additionally, it changes the URL of the `Hello World` IntelliJ IDEA section.
> Updating two links in the sidebar menu

- docs/_includes/_media-wrapper.html
- docs/index.md
This pull request adds a media wrapper to the main page of Arrow meta site to be able of show/hide the video of the Lambda World talk.
> Adding media wrapper for videos

- docs/_sass/components/_sidebar-menu.scss
Adding the `pointer-events: none` property, fixes the sidebar collapse behavior when clicking over the icon.
> Fixes sidebar deploy when clicking over the icon

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/MetaExtensions.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/declaration/PropertyAccessor.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/BreakExpression.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/ExpressionWithLabel.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/ReturnExpression.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/Property.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/BreakExpressionTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/BreakExpressionPlugin.kt
Break expression quote and template plus testing as well as the parent ExpressionWithLabel added!
> BreakExpression quote-and-template scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/MetaExtensions.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/BreakExpression.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/ContinueExpression.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/expressionwithlabel/ReturnExpression.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/ContinueExpressionTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/ReturnExpressionTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/ContinueExpressionPlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/ReturnExpressionPlugin.kt
`ContinueExpression` quote and template scope plus adjusted `ReturnExpression` with testing validation
#89
> ContinueExpression quote and template scope

- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/IdeSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/kotlinextension/KotlinIndicesSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/extensions/ExtensionProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/internal/registry/IdeInternalRegistry.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/editor/extension/ExtensionProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/initial/InitialIdePlugin.kt
resolves #246 KotlinIndicesHelperExtension is not registered as an ide Extension - check `KotlinCoreEnvironment# registerPluginExtensionPoints`.
Thus we have to manually add it. 
Furthermore, I discovered redundancies in Meta's Interpreter and flatten the registration process.
Turns out prior to this we could only register extensions, which were known to the `CoreApplicationEnvironment`. That method is only sufficient in Testing Environment. The technique proposed here is abstracting that process to any environment.  
To SumUp, `KotlinIndicesHelperExtension` has an unclear position to me in the ide. I am in contact with Alex from Jetbrains, who may give us more intel on that.
> Ide support for KotlinIndicesHelperExtension

- docs/_sass/components/_doc-content.scss
- docs/index.md
This PR adds a css class to the gif image in the landing docs in order to make it responsive.
Fixes #329
> Responsive gif image

- compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/psi/Converter.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/MetaExtensions.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/ScopedList.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/WhenExpression.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/NamedFunction.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/Property.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/TypeAlias.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/stub/typeparameterlistowner/TypeParameterListOwner.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/TypeAliasTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/TypeAliasPlugin.kt
> TypeAlias Quote and Template Testing Validation

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/notstubbed/FunctionLiteral.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/nameddeclaration/notstubbed/KtFunctionNotStubbed.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/FunctionLiteralTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/IfExpressionTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/FunctionLiteralPlugin.kt
> FunctionLiteral Quote and Template Scope Testing Validation

- compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/psi/Converter.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/MetaExtensions.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/element/PackageDirective.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/filebase/File.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/PackageDirectiveTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/PackageDirectivePlugin.kt
> PackageDirective quote and scope

- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/IfExpression.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/IfExpressionTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/IfExpressionPlugin.kt
> Fix: IfExpression testing and added validation

- compiler-plugin/src/main/kotlin/arrow/meta/quotes/element/PackageDirective.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/expression/WhenExpression.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/ClassBodyPlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/PackageDirectivePlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/plugins/WhenExpressionPlugin.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/scope/templates/WhenExpressionTest.kt
- Remove `secondIdentity` for `PackageDirective`. Reason: if we have `identity` and `secondIdentity` for an element, it won't be possible to ensure the identity law.
- Move new declarations to `identity`.
- Check of quote output in any case.
cc @ahinchman1
> Fix for upcoming identity law

- .github/workflows/kotlin-sync.yml
Just Kotlin version was considered by sync bot so far.
With this pull request, **sync bot** will keep Kotlin, Kotlin IDEA and Intellij IDEA versions updated.
**Sync bot** will create a pull request tomorrow morning to update to latest versions.
Add tests with latest Kotlin DEV version and latest Kotlin EAP version to **sync bot**.
> Sync: consider Kotlin, Kotlin IDEA and Intellij IDEA versions

- .github/workflows/publish_artifacts.yml
- compiler-plugin/src/main/kotlin/arrow/meta/plugins/helloWorld/DummyPlugin.kt
- gradle-plugin/build.gradle
- gradle-plugin/gradle.properties
* Publish snapshots for Gradle Plugin in OSS (oss.jfrog.org)
* Use Gradle Plugin Portal for releases
In case of failure with the snapshot version of Arrow Meta Compiler Compiler, all the versions in Gradle Portal will be affected now. This pull request prevents that situation.
* Add configuration to get `uploadArchives` task for Gradle Plugin in case of snapshot versions.
* Remove the unnecessary configuration to publish on Gradle Plugin portal in case of release versions.
* Add conditions to execute publication steps.
* Update documentation with the new guideline.
* Update Gradle Plugin metadata (website, description, etc).
> Gradle Plugin: publish snapshots in OSS

- README.md
- docs/index.md
Snapshot versions are published on OOS now. It will be added again with the first release version.
> Remove Gradle Plugin badge

- .github/workflows/kotlin-sync.yml
- build.gradle
- Remove EAP repository from `build.gradle` by default.
- Add DEV or EAP repository according to the test.
- Check `compiler-plugin` with latest Kotlin DEV version and latest Kotlin EAP version. 
- Create an issue in case of failure.
> Sync: test latest Kotlin EAP and DEV versions

- .github/workflows/kotlin-sync.yml
Because there are DEV or EAP versions that don't include `-eap-` or `-dev-`.
> Sync: improve issue titles

- .github/workflows/build_artifacts.yml
- .github/workflows/kotlin-sync.yml
- .github/workflows/sandbox/1.4.0-dev-191-65.diff
- .github/workflows/sandbox/README.md
- Fixes for `1.4.0-dev-191-65` in a patch file.
- Update **Build Check** to test upcoming versions with incompatible changes for every pull request.
- Update **Sync Bot** to consider patch files. For instance, when Kotlin 1.4.0 is released, the bot will create a pull request with all the necessary changes to jump to `1.4.0.`
- Add `.github/workflows/sandbox/README.md` with all the details.
One of the results of this PR can be seen in the [build check log](https://github.com/arrow-kt/arrow-meta/pull/373/checks?check_run_id=358836273):
```
Is there an upcoming version to check?
Checking .github/workflows/sandbox/1.4.0-dev-191-65.diff ...
For version 1.4.0-dev-191-65 ...
...
modified:   compiler-plugin/src/main/kotlin/arrow/meta/MetaCliProcessor.kt
modified: …
```
> Fixes for 1.4.0-dev-191-65 and how to manage upcoming versions

- idea-plugin/build.gradle
- idea-plugin/src/main/resources/META-INF/plugin.xml
- idea-plugin/src/main/resources/META-INF/pluginIcon.svg
- idea-plugin/src/main/resources/META-INF/pluginIcon_dark.svg
This **minor** PR tries to improve the documentation about IDEA plugin. These data will be shown in the Intellij IDEA plugin page and in the list of installed plugins.
For instance, from installed plugins:
Though the icon is shown correctly, it doesn't have the desired properties: http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html. It would be necessary to resize to 32x36 and then change the size to 40x40 with offset `x=4` and `y=2`.
The logo for a dark theme:
```
idea-plugin/src/main/resources/META-INF/pluginIcon_dark.svg
```
could be improved:
**Arrow** below **Arrow Meta** is the "vendor". It allows to look for other plugins published by the same "vendor".
> Update Arrow Meta Intellij IDEA Plugin documentation

- .github/workflows/publish_artifacts.yml
- .github/workflows/templates/updatePlugins.xml
- idea-plugin/build.gradle
- Minor change in `idea-plugin/build.gradle` to have `patchPluginXml` task.
- Add a template for IDEA plugin repository:
* It's useful for installing IDEA plugin when adding a new repository. However, that's not the main purpose. See the following point :wink: 
* It's useful for trying to install IDEA plugin from Gradle Plugin. It's necessary to have a way to download it. And the version will match with the current Gradle Plugin (see #245).
- Update publish artifacts task:
* Add the same `since-build` and `until-build` as Kotlin IDEA plugin.
* Publish the IDEA plugin repository file in S3 bucket to have URLs like `https://meta.arrow-kt.io/artifacts/idea-plugin/snapshots/<version>/updatePlugins.xml`
> IDEA Plugin: configuration for installation

- idea-plugin/build.gradle
Checks:
- New content of the jar file
- Installation from settings
- Installation from `plugins` directory
Errors (#398 ) disappeared and the plugin is loaded OK when opening a project:
```
(...)
it's the IDEA plugin
(...)
```
> IDEA Plugin: add compiler-plugin

- build.gradle
- gradle-plugin/build.gradle
- Move `maven-publish` from Arrow Meta Gradle Plugin to all the modules.
- Fix custom tasks from main `build.gradle`.
> Configuration: fix custom tasks from main build.gradle

- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt
- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/InstallIdeaPlugin.kt
Instead of installing Arrow Meta IDEA plugin when applying the Arrow Meta Gradle Plugin, it's installed by a Gradle task.
From command line:
When applying the Gradle plugin from Intellij IDEA:
When running `install-idea-plugin` task from Intellij IDEA:
Other situations from Intellij IDEA:
> Gradle plugin: install IDEA plugin from a Gradle task

- .github/workflows/templates/updatePlugins.xml
The specific snapshot version (like `1.3.61-20200109.183401-23`) is only known after publishing the artifact and it must match with the version in `plugin.xml` (inside jar file).
This minor PR fixes the version in the repository and adds additional information which will be available before installing the plugin.
**Note**: the specific version (in case of working with snapshot versions) can be checked in the plugins directory as well (it appears in the jar file).
> IDEA plugin: fix version in the repository

- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/InstallIdeaPlugin.kt
**Probable cause:** choose runtime plugin
**error**: Symbol is declared in module 'java.xml' which does not export package 'com.sun.org.apache.xerces.internal.parsers'
thanks @rachelcarmena !
> fix to not export package probably caused for choose runtime plugin

- compiler-plugin/src/main/kotlin/arrow/meta/internal/Noop.kt
- docs/_data/sidebar.yml
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/lineMarker/LineMarkerSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/utils/IdeUtils.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/helloworld/DummyPlugin.kt
- adds mergeable LineMarkers indicated with *M* suffix in `addLineMarkerProviderM`
- current Rendering targets `Descriptors`
- One can render `KtElements` with Fir API's like in the following example, but I'd add Fir support in another PR: 
```kotlin
fun KtCallableDeclaration.toFir(phase: FirResolvePhase = FirResolvePhase.BODY_RESOLVE): String =
buildString { getOrBuildFir(firResolveState(), phase).accept(FirRenderer(this@StringBuilder)) } 
```
Due to the different primitives in contrast to `DescriptorRenderer`:
`FirRenderer`: 
`DescriptorRenderer`:
> mergeable LineMarkers & further Rendering options

- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/resolve/MetaSyntheticPackageFragmentProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/initial/InitialIdePlugin.kt
- idea-plugin/src/main/resources/META-INF/plugin.xml
removes the registration of `MetaSyntheticPackageFragmentProvider` in plugin.xml and uses the one from Meta. 
And Helps #462
> PackageFragmentProvider in Meta DSL

- compiler-plugin/build.gradle
In order to use the Gradle process when running the tests.
> Configuration to run tests

- .github/workflows/publish_artifacts.yml
*Reason*: Kotlin team is no longer creating files per IDEA branch number version.
> Publish: remove branch number consideration

- idea-plugin/src/main/kotlin/arrow/meta/ide/ArrowHighlightingPassFactory.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/resolve/QuoteSystemCache.kt
- idea-plugin/src/main/resources/META-INF/plugin.xml
- idea-plugin/src/test/kotlin/arrow/meta/ide/phases/resolve/QuoteTestUtils.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/phases/resolve/QuoteTransformationTest.kt
@raulraja This is finally some progress with this unnerving issue of broken highlighting.
The reason was, that resolving was triggered very early during highlighting (i.e. by the folding outline builder). At this point the initial transformation wasn't finished yet. Therefore the highlighting working with missing or incomplete Quote transformation datat. This resulted in broken highlighting.
Although we forced a restart of highlighting, this did not seem to be enough. I did not dig into the highlighting engine to find out why.
This PR waits for the initial highlighting in a .kt file until the initial Quote transformations, which are registered when the project is opened, are finished.
Questions:
- This approach is a bit brutal as it delays highlighting. But I don't know of another …
> Force flush of Quote transformations before highlighting

- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/IdeEnvironment.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/IdeTest.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/dsl/IdeTestSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/IdeTestInterpreter.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/resolution/ResolutionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/types/LightTestSyntax.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/comprehensions/ComprehensionsTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/higherkinds/HigherKindTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/lens/LensTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/purity/PurityTest.kt
Based on some feedback in testing. There is a new testing dsl in the Ide, 
which supports features described in the PluginScope `e.g.: IdeMetaPlugin`, which can then be used to describe tests. 
The data type IdeTest has now 3 fields the `code`, `test` to define a test and the expected result. 
The remaining dependencies to unfold that data structure into a test are now subject to functions and are not implicitly added. 
So we get the best out of both worlds, ascribing different interpreters for tests and a neat DSL without duplicating code.
> Revamp Ide Testing DSL

- .github/workflows/sandbox/1.3.70-eap.diff
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/application/ApplicationSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/application/ProjectLifecycle.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/internal/IdeRegistrar.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/internal/registry/IdeInternalRegistry.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/application/ApplicationProvider.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/quotes/QuotePlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/IdeTestInterpreter.kt
adds a better encoding for project and application services.
```kotlin
addProjectService(
service = MyService::class.java,
instance = { project: Project, hijackedService: MyService? ->
object : MyService {
override fun printLn(f: KtNamedFunction): Unit =
println("Function: ${f.name} returns ${f.resolveToDescriptorIfAny()?.returnType ?: "ERROR"}")
}
}
)
```
This algebra also provides the hijacked services from 3rd parties, given that the services has been instatiated by a plugn one depends.
> reencode Services

- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/IdeTest.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/IdeTestInterpreter.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/resolution/ResolutionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/types/LightTestSyntax.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/comprehensions/ComprehensionsTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/higherkinds/HigherKindTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/lens/LensTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/purity/PurityTest.kt
adds boolean logic to tests algebra
turns around `<A, F>` to `<F, A>` signatures
> clean up on testing dsl Ide

- idea-plugin/build.gradle
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/annotators/refinement.kt
cc @i-walker 
Unhandled exceptions are passed to IntelliJ's `DefaultErrorHandler`
`DefaultErrorHandler` detects the plugin, which likely caused the exception. That's the kotlin plugin for the ThreadDeath exception, because the first frame of the stack trace belongs to the Kotlin plugin.
We can't override that extension of the Kotlin plugin.
The error reporter of the plugin is then queried if the error should be reported.
`org.jetbrains.kotlin.idea.reporter.KotlinReportSubmitter#showErrorInRelease` is the implementation of the Kotlin plugin. System property `val KOTLIN_FATAL_ERROR_NOTIFICATION_PROPERTY = "kotlin.fatal.error.notification"` controls if errors should be suppressed.
- Now we can use this property to hide the ThreadDeath exception.
**That's a rather bad hack, but the only way I …
> Suppress thread death error is caused by the Kotlin script engine

- build.gradle
- docs/build.gradle
It's available for all the modules and it just makes sense for `docs` module.
> Relocate Ank plugin

- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/folding/unionTypes.kt
Visually limiting the amount of types used by the Union (up until 5) when its folded and trucated with `...`.
> Union folding truncate

- compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/resolve/scopes/ProofsSyntheticScopes.kt
We want to be able to click on a type class syntax method call to go to its declaration. E.g:
When we generate the synthetic scope for function members we are losing information about the `source` element on the descriptor. We need to explicitly call to `setPreserveSourceElement()` each time we create a custom copy for a function description using the builder, otherwise it'll likely drop it. Source is needed for the IDE to track the declaration down and enable navigation.
> Fix typeclass syntax navigation

- docs/_sass/components/_doc-header.scss
Sets `doc-header` sticky position in small screen size for docs section.
This closes #560
> set doc-header sticky position in small size

- gradle-plugin/build.gradle
`runtimeOnly` is not considered when publishing the artifact into OSS (just local repository).
List of dependencies for gradle-plugin before this fix: https://oss.jfrog.org/artifactory/oss-snapshot-local/io/arrow-kt/gradle-plugin/1.3.61-SNAPSHOT/gradle-plugin-1.3.61-20200424.120403-65.pom
```
<dependencies>
<dependency>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-scripting-compiler-embeddable</artifactId>
<version>1.3.61</version>
<scope>runtime</scope>
</dependency>
<dependency>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-script-util</artifactId>
<version>1.3.61</version>
<scope>compile</scope>
</dependency>
<dependency>
<groupId>org.jetbrains.kotlin</groupId>
<artifactId>kotlin-stdlib</artifactId>
<version>1.3.61</version>
<scope>runtime</scope> …
```
> Fix dependencies for gradle-plugin

- .github/workflows/publish_artifacts.yml
Current private repository for Arrow Meta Intellij IDEA Plugin is thought to be available from Arrow Meta Gradle Plugin and to install a correspondent version. 
However, it would be necessary to have private repositories without a specific version in its URL for the latest version (snapshot or release). They're added with this PR.
> Add another Intellij IDEA plugin repository

- compiler-plugin/build.gradle
- gradle-plugin/build.gradle
- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt
- Compiler Plugin define all the transitive dependencies
- Gradle Plugin just needs the Compiler Plugin dependency
- Checked with [the playground for typeproofs](https://github.com/arrow-kt/arrow-typeproofs)
- Shadowed JAR content doesn't change with this improvement.
> Fix #499: remove hard-coded dependencies for Gradle Plugin

- prelude/build.gradle
- prelude/gradle.properties
The artifact is being published in local repository with the module name (`prelude`) and in OSS repository with the artifact ID (`arrow-meta-prelude`). 
This PR fixes the name for `arrow-meta-prelude` for local repository because that library will be part of Arrow.
> Rename artifact ID for prelude module

- .github/workflows/build_artifacts.yml
- .github/workflows/publish_artifacts.yml
- build.gradle
PR on `ja-gradle-testing` branch by @jansorg and @i-walker 
Install Arrow Meta dependencies to run tests for Arrow TypeProofs Playground from Arrow Meta IDEA Plugin.
> Fix #589. Install local dependencies for tests

- compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/Node.kt
- compiler-plugin/src/main/kotlin/arrow/meta/internal/kastree/ast/psi/Converter.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/analysis/ElementScope.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt
- compiler-plugin/src/main/kotlin/arrow/meta/quotes/filebase/File.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/TransformNewSourceTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformNewSourcePlugin.kt
- meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt
- meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
**This is related to https://github.com/arrow-kt/arrow-meta/issues/591** 
This PR brings a new feature to `Transform.newSources` api that allows we set custom source pathes in its generation:
```kotlin
Transform.newSources(
"""
package arrow  
class ${name}_Generated
""".file("${name}_Generated.kt", "build/generated/source/kapt/test/files")
)
```
an other `file` function with a second parameter allows us to specify its path, also it could be used with multi source generation:
```kotlin
Transform.newSources(
"""
package arrow       
class ${name}_Generated 
""".file("${name}_Generated", "build/generated/source/kapt/test/files"),
"""
package arrow      
class ${name}_Generated_2
""".file("${name}_Generated_2", "build/generated/source/kapt/test/files/source")
)
```
With that it can be used …
> Dynamic transform new source path

- compiler-plugin/src/test/kotlin/arrow/meta/plugins/refinement/RefinementTests.kt
It's necessary to re-run checks because it fails randomly.
> Disable flaky test reported in #581 until it's fixed

- .github/workflows/publish_artifacts.yml
**Reason**: failures on publication from #608 because generated sources during tests are being packaged when uploading the artifacts.
> Publication: remove previous build

- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt
- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/InstallIdeaPlugin.kt
- idea-plugin/build.gradle
* **Unify IDE Plugin name**: It shouldn't end with `Plugin` word.
* **Add Gradle tasks metadata**: It's useful for finding the task to run it. Related documentation will be simpler.
> Configuration: unify IDE Plugin name and add Gradle tasks metadata

- docs/docs/_sass/components/_code.scss
- docs/docs/_sass/components/_doc-content.scss
> Doc: fix style

- docs/build.gradle
* PR on `ide-update`
* Just fixing `Build Documentation` check.
`com/intellij/testFramework/fixtures/CodeInsightTestFixture.class` is included in `testFramework.jar` instead of `idea.jar` in `ideaIC-2020.1`.
I didn't remove `idea.jar` because it's necessary for other classes.
> Update 2020.1: fix doc generation

- README.md
Removing the `-Dorg.gradle.debug=true` option from the readme.
> Remove gradle debug option from readme.

- .github/workflows/sandbox/1.3.70-eap.diff
@danimontoya `expression.descriptor` changes to  `expression.symbol.descriptor` for 1.3.7x.
> Fix patch for #631

- compiler-plugin/src/main/kotlin/arrow/meta/MetaPlugin.kt
- compiler-plugin/src/main/kotlin/arrow/meta/log/Log.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/comprehensions/ComprehensionsTest.kt
- idea-plugin/build.gradle
- idea-plugin/src/main/kotlin/arrow/meta/ide/IdeMetaPlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/ProofsIdePlugin.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/quotes/QuotePlugin.kt
- idea-plugin/src/main/resources/META-INF/plugin.xml
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/proofs/folding/FoldingBuilderTest.kt
- idea-plugin/src/test/kotlin/arrow/meta/ide/plugins/proofs/markers/CoercionTest.kt
This PR temporary disables `Log.Verbose`, IDE Quote support and it re-enables the IDE support for Refinement.
- Left `Log.Verbose` disabled, we probably want to re-enable this later?
- Left `"org.celtric.kotlin:kotlin-html:$KOTLIN_HTML_VERSION"` as `implementation`. We need to double check wheter that change can stay.
cc\\ @raulraja
> Temp fix IDE issues

- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/markers/ProofMarkers.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/markers/predef.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/proofs/markers/valueArgumentCoercion.kt
Same fix that we did for coercion within value arguments with the mergeableLineMarkers.
Performance warning: LineMarker is supposed to be registered for leaf elements only.
`KtDeclaration` isn't a leaf.
This fixes performance line markers for: Refinement, Coercion, Extension, Given
> Performance warning: LineMarker is supposed to be registered for leafs only

- idea-plugin/src/main/kotlin/arrow/meta/ide/internal/registry/IdeInternalRegistry.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/phases/additional/AdditionalIdePhase.kt
- idea-plugin/src/main/resources/META-INF/plugin.xml
This allows users to define an `ExtensionPhase` that is registered as part of the IdeInternalRegistry, such that plugin devs and alike are no longer restricted by the set of Ide extensions that are implemented in Meta, but can define their own libraries on top of it and benefit from the DSL at the same time. 
I will link an example once, I can pull the Snapshot from master. 
But it boils down to composing one's algebra as Meta does in IdeSyntax compose them with `arrow.meta.ide.MetaIde` and registering them in the overridden service.
```kotlin
interface MySyntax : ExtensionYSyntax, ExtensionZSyntax // and many more each of them defing extension functions based on MyIdeSyntax
interface MyIdeSyntax : MySyntax, MetaIde
```
One example with an imaginary extension called `YExtension`: …
> 3rd party extensions in Meta

- .github/workflows/build_artifacts.yml
- .github/workflows/kotlin-sync.yml
Reasons:
- WIP #706
- They should be updated after #706 because of using `1.4-M3` (not `1.4` yet)
> Configuration: disable next version checks

- compiler-plugin/build.gradle
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/typeclasses/GivenTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/typeclasses/TypeClassesTest.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/typeclasses/kinds.kt
- meta-test/build.gradle
- meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- prelude/src/main/kotlin/arrow/extension.kt
- prelude/src/main/kotlin/arrow/synthetic.kt
- Remove `arrow-core-data` dependency
- Replace `arrow-annotations` dependency by moving `extension` and `synthetic` to `arrow-meta-prelude`.
> Clean dependencies

- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/application/ApplicationSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/action/AnActionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/color/ColorSettingsSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/documentation/DocumentationSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/hints/HintingSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/icon/IconProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/lineMarker/LineMarkerSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/syntaxHighlighter/SyntaxHighlighterSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/extensions/ExtensionProviderSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/ui/dialogs/DialogSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/ui/popups/PopupSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/ui/toolwindow/ToolWindowSyntax.kt
- idea-plugin/src/main/kotlin/arrow/meta/ide/testing/env/IdeTestInterpreter.kt
`playground` Ank modifier is being used for Arrow IDE Plugin examples. However, it's not working now because it's necessary to provide more libraries (Meta and Kotlin IDE plugin).
This PR removes the use of that Ank modifier.
> Remove playground for Arrow IDE Plugin examples

- docs/build.gradle
Current errors when validating the documentation for `1.4.0-rc`. There is no clue to solve them.
If all the dependencies from compile classpath and runtime classpath (295 dependencies) are added then Ank raises a lot of errors from conflicts between them so the classpath for Ank validation includes:
* The whole runtime classpath: 31 dependencies; some of them with specific Kotlin version for Ank
* Specific dependencies from Intellij IDEA + Kotlin IDEA Plugin
The classpath for Ank validation will include:
* Specific dependencies with the current Kotlin version: 24 dependencies
* Specific dependencies from Intellij IDEA + Kotlin IDEA Plugin
That control about dependencies for Ank validation is useful for upgrades because just the expected dependencies are considered.
> Configuration: specific classpath for Ank validation

- compiler-plugin/src/main/kotlin/arrow/meta/log/Log.kt
- compiler-plugin/src/main/kotlin/arrow/meta/phases/codegen/ir/IrUtils.kt
- compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/ir/ProofsIrCodegen.kt
- compiler-plugin/src/main/kotlin/arrow/meta/plugins/proofs/phases/resolve/GivenUpperBound.kt
Resolves the GivenProof resolution, which caused the failing GivenTests.
Prior to 1.3.71 there was a member `descriptor`, which would return the resolved call at the call-site. It has been removed ever since in this [PR](https://github.com/JetBrains/kotlin/commit/ed79ab68abb0969c725e2c0b7d377866f41ac070#diff-5d9c42c2e76ac014d97644460546e5af). 
This PR resolves the Kotlintype for type parameters so that calculating the upper bound resolves with the concrete type at call-site and not the generic type parameter, which is found in the ValueparameterDescriptor.
> Fixes GivenTests

- meta-test/src/main/kotlin/arrow/meta/plugin/testing/Compilation.kt
Closes #728 thanks to the idea by @Starmel :tada: 
It filters the compilation output during testing when avoiding lines starting with "e:"
> Fix #728 - Filter compilation output during testing

- build.gradle
- gradle/build-idea-plugin.gradle
This PR continues https://github.com/arrow-kt/arrow-meta/pull/740 in order to use the same artifacts that are published into repositories for local tests.
> Fix publish and run IDE

- compiler-plugin/build.gradle
- docs/build.gradle
- gradle.properties
It's only used for documentation (Arrow Ank) so far.
> Upgrade to Arrow 0.11.0

- .github/workflows/publish_artifacts.yml
- docs/docs/setup.md
- gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ArrowGradlePlugin.kt
**Fixes this issue**: when installing Arrow Meta IDE Plugin SNAPSHOT version, the IDE doesn't show notifications to update the plugin.
**Changes**:
* Fix deployment of custom repository
* Update messages from the Arrow Meta Gradle plugin
* Update setup documentation
* Tiny code improvements
> IDE Plugin: allow update when SNAPSHOT

- compiler-plugin/src/main/kotlin/arrow/meta/quotes/Quote.kt
- compiler-plugin/src/test/kotlin/arrow/meta/plugins/refinement/RefinementTests.kt
- docs/build.gradle
- meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt
Remove manipulation of paths because it removes the first file separator for absolute paths.
It's not possible to use absolute paths when transforming sources now, just relative paths: https://github.com/arrow-kt/arrow-meta/blob/master/compiler-plugin/src/test/kotlin/arrow/meta/quotes/transform/plugins/TransformNewSourcePlugin.kt#L109
> compiler-plugin: fix paths when transforming sources

- .github/workflows/publish_artifacts.yml
- README.md
- build.gradle
- docs/build.gradle
- docs/docs/index.md
- docs/docs/setup.md
- gradle-plugin/build.gradle
- gradle.properties
- Change in `arrow` repository: https://github.com/arrow-kt/arrow/pull/2371
- Create new secrets:
* `SONATYPE_USER`
* `SONATYPE_PWD`
* `ORG_GRADLE_PROJECT_signingKey`
* `ORG_GRADLE_PROJECT_signingPassword`
- Replace OSS JFrog snapshots repository by Sonatype OSSRH snapshots repository.
- Replace Bintray repository by Sonatype OSSRH releases repository (a staging repository is created before).
- Update badges.
- Update documentation.
- Remove Bintray secrets.
- Notify the new SNAPSHOTS repository.
- Remove `1.4.10-SNAPSHOT` from OSS JFrog to avoid misunderstandings.
- Update `arrow-meta-examples`.
> Configuration: remove Bintray et al.

- arrow-refined-types/build.gradle
- arrow-refined-types/src/commonTest/kotlin/arrow/refinement.tests/RefinedArb.kt
- build.gradle
- docs/build.gradle
- gradle-plugin/build.gradle
- gradle.properties
- Add `js` target
- Update dependencies to make it work for both targets (IDE included)
- Small fix in tests to make them run for `js` target as well
- Remove `kotlin.stdlib.default.dependency=false` because of https://youtrack.jetbrains.com/issue/KT-46847
- Fix the application of Kotlin JVM plugin
- Extract and relocate code to be able to customize `clean` task
> Update multiplatform configuration

- gradle.properties
- gradle/subproject-mpp.gradle
To recover the use of `kotlin.stdlib.default.dependency` property
> Update MPP configuration

- .github/workflows/build_documentation.yml
Reasons:
* Unnecessary step
* It fails for pull requests from branches of other repositories
> Configuration: skip step for checking documentation

- plugins/liquid/arrow-refined-types/src/commonMain/kotlin/arrow/refinement/RefinementDSL.kt
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaDefaultErrorMessages.java
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaErrors.java
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintCollection.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/SolverInteraction.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR enables the analysis to work on `var` declarations and assignments. This is done by assigning fresh names to each new assignment of a variable; at a conceptual level the following code:
```kotlin
var x = 1
x = 2
return x
```
is "translated" into (but of course no translation takes place):
```kotlin
val x1 = 1
val x2 = 2
return x2
```
> Support for mutable variables

- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/continuations/ContSeq.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR fixes the handling of `return` nodes, which was incorrect until now, since it `abort`ed the whole computation from that point on. One important consequence was that post-conditions were *not* checked when appearing after a `return`, like in the following snippet:
```kotlin
fun f(x: Int): Int {
return 2.post("greater than 0") { it > 0 }
}
```
In a technical side, this PR changes the signature of the checking functions from `ContSeq<Unit>` to `ContSeq<Return>`. This additional piece of information tells whether we simply got to the end of the block (`NoReturn`) or we were explicit (`ExplicitReturn`). In the latter case we also record an explicit label if it appears. The core of the handling is in:
- `checkReturnExpression`, where we handle the `ExplicitReturn` case and continue if …
> Handle 'return' correctly

- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaDefaultErrorMessages.java
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaErrors.java
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/SolverInteraction.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR fixes two problems with the previous naïve approach to variables:
1. Shadowing was not taken into account, so the system would get confused if you declare, for example, a `val x` within the body of a conditional.
- This has been solved by keeping an additional `CurrentVarInfo` in which the "top-most" declaration of a name appears earlier in the list. This maps each name to its "SMT name".
- To keep the names nice for the non-shadowing case, the "SMT name" is initialized to the one declared by the user, and only further re-declaration create a new name. In particular, the parameter names receive the same "SMT names" as they have.
2. For mutable variables always the "last" assignment was chosen. However, this is **unsound** in general; for mutable variables **only the invariant** is …
> Scoping fixes

- plugins/liquid/arrow-refined-laws/src/commonMain/kotlin/arrow/refinement/BadExample.kt
- plugins/liquid/arrow-refined-types/src/commonMain/kotlin/arrow/refinement/RefinementDSL.kt
- plugins/liquid/arrow-refined-types/src/commonTest/kotlin/arrow/refinement.tests/NetworkTests.kt
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/FormulaRenderer.kt
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaDefaultErrorMessages.java
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaErrors.java
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintCollection.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/DeclarationConstraints.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/SolverInteraction.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/SolverState.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/ir/ConstraintsAnnotations.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/smt/FormulaExtensions.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
Based on discussions with @nomisRev, we simplify the constraints DSL to resemble what a user would be familiar with using functions like `kotlin.require`.
Additionally, based on a conversation with @serras and to prepare for better error messages, this PR tracks all user and internal messages associated with constraints and ensures they are persisted and deserialized from annotations.
> CU-yyb9hg Simplifies constraint DSL and persists user messages with formulae

- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR adds special treatment in the analysis for the functions `also`, `apply`, `let`, and `run`, when they are called with a lambda expression afterwords. The reason is that we can get a much better analysis than resorting to a future higher-order function analysis.
Technically, the implementation is easy. For example, when we find code like:
```
thing.let { it + 1 }
```
what the analysis does is:
- analyze the argument `thing` as usual,
- create a new context in which `it` is equal to `thing`,
- analyze the body of the function, in which `it` now points to the right value,
- state that the return value of the whole computation is the return value of the block.
Since there are essentially four combinations:
1. whether `thing` goes in the block as `this`, or as `it`/given lambda …
> Special treatment for control flow functions

- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintChecks.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/ConstraintCollection.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/smt/Solver.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR adds support for:
This is done by keeping an additional `null` uninterpreted function, which tells us whether we are in a definitely-null (if true), definitely-not-null (if false), or unknown situation.
> [Analysis] Nullability (?. and ?:)

- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaDefaultErrorMessages.java
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaErrors.java
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Declarations.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/collect/ConstraintCollection.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/errors/ErrorMessages.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/state/SolverInteraction.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR changes the analysis of declarations to go well with subtyping:
- check that the Liskov Substitution Principle is obeyed in overridden members
- look for constraints in overridden members if they cannot be found in the current one
> [Analysis] Subtyping

- libs/meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilationAssertions.kt
- libs/meta-test/src/main/kotlin/arrow/meta/plugin/testing/CompilerTestDSL.kt
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaDefaultErrorMessages.java
- plugins/liquid/refined-types-plugin/src/main/java/arrow/meta/plugins/liquid/errors/MetaErrors.java
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Declarations.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/EntryPoint.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/Expressions.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/model/CheckData.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/check/model/ReturnPoints.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/collect/ConstraintCollection.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/collect/ConstraintSearch.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/errors/ErrorMessages.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/phases/analysis/solver/state/SolverState.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/smt/FormulaExtensions.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/smt/Solver.kt
- plugins/liquid/refined-types-plugin/src/main/kotlin/arrow/meta/plugins/liquid/smt/utils/NameProvider.kt
- plugins/liquid/refined-types-plugin/src/test/kotlin/arrow/meta/plugins/liquid/LiquidDataflowTests.kt
This PR's goal is to handle constructors by:
> [Analysis] Constructors

- libs/gradle-plugin-commons/src/main/kotlin/arrow/meta/plugin/gradle/ArrowMetaGradlePlugin.kt
- plugins/analysis/gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/AnalysisGradlePlugin.kt
- plugins/optics/optics-gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/OpticsGradlePlugin.kt
- plugins/proofs/proofs-gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ProofsGradlePlugin.kt
This is needed to apply several compiler plug-ins over the same project.
> Allow different extension names for Meta plug-ins

- gradle/projects.libs.versions.toml
- libs/gradle-plugin-commons/src/main/kotlin/arrow/meta/plugin/gradle/ArrowMetaGradlePlugin.kt
- plugins/analysis/gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/AnalysisGradlePlugin.kt
- plugins/optics/optics-gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/OpticsGradlePlugin.kt
- plugins/proofs/proofs-gradle-plugin/src/main/kotlin/arrow/meta/plugin/gradle/ProofsGradlePlugin.kt
The goal is to be able to apply more than one plug-in in a project, which now fails with the error:
```
> Task :compileKotlin
'compileJava' task (current target is 17) and 'compileKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: Multiple values are not allowed for plugin option arrow.meta.plugin.compiler:generatedSrcOutputDir
Plugin "arrow.meta.plugin.compiler" usage:
generatedSrcOutputDir arrow-meta-gen-src-output-dir
Directory to locate generated sources
```
> Use different compiler ids for each plugin

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/smt/utils/FormulaToKotlin.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
This PR changes part of the logic for showing a formula back to a user, and fixes some corner cases:
- better handling of negation: whereas before we had `(! x > 0)` now we proper show `!(x > 0)`,
- special cases for negating equality or comparisons in formulae,
- better handling of parentheses,
- the `null` special function is now shown as in `x == null`
> [Analysis] Improvements to formula dump

- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/ast/KotlinInterpreter.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinLocalVariableDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinPropertyDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinValueParameterDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinVariableDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinVariableDescriptorWithAccessors.kt
Sometimes the Kotlin compiler surprises us with more members of the `Descriptor` hiearchy. For most of them we do not really want to do something special, so I've reworked the `model` call to take care of those with a fallback implementation.
This has bitten me in particular while using the Analysis plug-in in an external project:
```
e: kotlin.NotImplementedError: An operation is not implemented: Missing impl for org.jetbrains.kotlin.resolve.calls.util.FakeCallableDescriptorForObject@d1bb6a5 (org.jetbrains.kotlin.resolve.calls.util.FakeCallableDescriptorForObject)
at arrow.meta.plugins.analysis.phases.analysis.solver.ast.kotlin.ast.KotlinInterpreterKt.model(KotlinInterpreter.kt:46)
```
> [Analysis] Add more fallbacks to Kotlin analysis interpreter

- libs/arrow-meta/src/main/kotlin/arrow/meta/MetaCliProcessor.kt
- libs/arrow-meta/src/main/kotlin/arrow/meta/phases/analysis/DefaultElementScope.kt
- libs/arrow-meta/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
- libs/gradle-plugin-commons/src/main/kotlin/arrow/meta/plugin/gradle/ArrowMetaGradlePlugin.kt
- plugins/analysis/example/build.gradle.kts
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/AnalysisPlugin.kt
- plugins/analysis/kotlin-plugin/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
- plugins/analysis/laws/build.gradle.kts
- plugins/optics/optics-plugin/src/main/kotlin/arrow/meta/OpticsMetaPlugin.kt
- plugins/optics/optics-plugin/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
- plugins/proofs/proofs-plugin/src/main/kotlin/arrow/meta/ProofsMetaPlugin.kt
- plugins/proofs/proofs-plugin/src/main/resources/META-INF/services/org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
I think this solves #926. The idea is that each plug-in should provide its own local configuration (which you can still override in a global fashion by setting the `arrow.meta.generated.src.folder` property). At least the plug-ins can now be applied without problems.
> Use different MetaCliProcessors

- libs/arrow-meta/src/main/kotlin/arrow/meta/quotes/classorobject/ClassOrObject.kt
- libs/arrow-meta/src/main/kotlin/arrow/meta/quotes/filebase/File.kt
- libs/arrow-meta/src/main/kotlin/arrow/meta/quotes/modifierlistowner/ModifierList.kt
- libs/arrow-meta/src/main/kotlin/arrow/meta/quotes/modifierlistowner/TypeReference.kt
- libs/arrow-meta/src/test/kotlin/arrow/meta/quotes/scope/templates/ClassBodyTest.kt
Fix for https://github.com/arrow-kt/arrow-meta/issues/893
Add a whitespace as a separator for `@annotations` in `ClassOrObject`
> [WIP] Add whitespace as separator for annotations

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Declarations.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Parameters.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/state/SolverInteraction.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/state/SolverState.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/smt/utils/FieldProvider.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
I ran into a bug while working on the back-end example; it turned out that the numbering for fields was not correctly initialized at all spots. This was the result of one of the optimizations we applied, of not introducing field names until required; however some places were missing. I've added the check now to `addConstraint`, which is the single point of constraint addition in the system.
> [Analysis] Fix problems with fields

- gradle/projects.libs.versions.toml
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/context/elements/StringTemplateExpression.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/errors/ErrorIds.kt
- plugins/analysis/kotlin-plugin/build.gradle.kts
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/ast/KotlinInterpreter.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/elements/KotlinElement.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/elements/KotlinStringTemplateExpression.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
1. Support for string templates
2. Change the level of "unreachable code" to a warning in SARIF, to align it with the Kotlin and Java plug-ins
These are both required for the `backend-example` to work well
> [Analysis] Two small things

- gradle/projects.libs.versions.toml
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/DescriptorUtils.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ResolvedCallUtils.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/context/descriptors/Annotated.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FindDescriptor.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FromAnnotations.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/FromDSL.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/collect/model/DeclarationConstraints.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/search/ConstraintSearch.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/smt/FormulaExtensions.kt
- plugins/analysis/example/src/commonMain/kotlin/arrow/analysis/BadExample.kt
- plugins/analysis/java-plugin/src/main/kotlin/arrow/meta/plugins/analysis/java/ast/JavaResolutionContext.kt
- plugins/analysis/kotlin-plugin/build.gradle.kts
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/KotlinResolutionContext.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/ir/ConstraintsAnnotations.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
- plugins/analysis/laws/src/commonMain/kotlin/arrow/analysis/laws/kotlin/Collections.kt
- plugins/analysis/types/src/commonMain/kotlin/arrow/analysis/RefinementDSL.kt
This fixes the problem with the following snippet:
```kotlin
fun <A> List<A>.allEqual = all { it == first() }
```
This would flag the call to `first()` as problematic, since we need to have a non-empty list. However, if the list if empty, `all` will never call the function, so we are good!
This is done by adding a new kind of annotation to explain in which cases the arguments are not evaluated, based on some property of the receiver:
```kotlin
@Law
inline fun <E> List<E>.allLaw(predicate: (x: E) -> Boolean): Boolean {
doNotLookAtArgumentsWhen(isEmpty()) { "empty lists have no elements" }
return all(predicate)
}
```
> [Analysis] Better analysis for empty lists

- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
- plugins/analysis/laws/src/commonMain/kotlin/arrow/analysis/laws/kotlin/Collections.kt
This PR implements 2 laws to the internals, that explicits axioms to `mapOf<K, V>` and `list.isEmpty()`. Before this PR pre conditions like this:
```kotlin
fun <E> List<E>.x(): Int {
pre(isEmpty()) { "list is not empty" }
return 1
}
val l = listOf<Int>().x()
```
and
```kotlin
fun <K, V> Map<K, V>.x(): Int {
pre(isEmpty()) { "map is not empty" }
return 1
}
val l = mapOf<Int, Int>().x()
```
breaks because there're no axioms for them.
> [Analysis] Empty mapOf and isEmpty laws

- gradle.properties
After checking the docs, it turns out that you cannot deploy `1.6.0-RC` and `2.0-SNAPSHOT` on the same repository, either everything is release or everything is SNAPSHOT.
> Everything is SNAPSHOT again

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Declarations.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Parameters.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/model/CheckData.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/model/Condition.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/model/CurrentVarInfo.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/model/VarInfo.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/smt/Solver.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
This fixes two bugs which were found by @nomisRev:
1. Built-in names were not properly escaped; calling a parameter `div` conflicted with the built-in `div` function from integers;
2. `if` without an `else` was not handled, resulting in a `NullReferenceException`.
> [Analysis] Handle if without else, escape built-in names

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/Primitive.kt
For some reason formulae with `*` make the SMT solver throw an exception. This PR just disables it.
> [Analysis] Disable times operator

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/Expressions.kt
- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/state/SolverInteraction.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
The tests @nomisRev has been doing have shown that sometimes we are too noisy about conflicting information about nullability. This usually comes because each usage of a possibly-nullable value, `?.`, `?:` or `as?` generates two possible "branches of execution", but in many cases those are repetitive and conflict (for example, we have a parameter of type `Int?`, so we have two branches; but then if we use `n?.let { ... }` we generate yet another two branches, one conflicting with the fact that `n` is or is not null).
This PR makes the inconsistency warnings less noisy when dealing with those operators.
> [Analysis] Be less picky about inconsistent nullability checks

- docs/docs/analysis/types/README.md
- docs/docs/analysis/wrappers/README.md
Hello
I saw following broken links on the Arrow Analysis docs.
https://arrow-kt.io/docs/meta/analysis/wrappers/
https://arrow-kt.io/docs/meta/analysis/types/#types-and-invariants
I couldn't verify if this solves the issue locally as I was unable to 'build the site'
However I guess the dangling `(` is the culprit.
> Fix broken documentation links

- docs/docs/analysis/README.md
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/ast/KotlinInterpreter.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinDeclarationDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinDeclarationDescriptorWithVisibility.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinFunctionDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinModuleDescriptor.kt
- plugins/analysis/kotlin-plugin/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/ast/kotlin/descriptors/KotlinVariableDescriptor.kt
Fixes #1001 
It also contains a small update to the docs that explains how to disable precise Java tracking, which is required for Arrow Analysis to work in Android projects
> [Analysis] Handle every declaration descriptor in Kotlin

- libs/gradle-plugin-commons/src/main/kotlin/arrow/meta/plugin/gradle/ArrowMetaGradlePlugin.kt
Fixes #1026 
This should allow using any Gradle version, since we stop depending on internal API on 7.x. The `Version` class is available only in Java from version 9, but this should not be a problem.
> Do not use Gradle's internal VersionNumber

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/smt/Solver.kt
- plugins/analysis/kotlin-plugin/src/test/kotlin/arrow/meta/plugins/analysis/AnalysisTests.kt
Fixes #1031 
The problem was that SMT names are escaped, but the ones we use internally (`field`, `int`, ...) were not. This PR adds them and a small test case.
> [Analysis] Escape more internal names

- plugins/analysis/common/src/main/kotlin/arrow/meta/plugins/analysis/phases/analysis/solver/check/EntryPoint.kt
I think this fixes #1032, but I'm not 100% sure because I cannot test code with several plug-ins.
@mkotsbak would you be open to trying this version in your project? we can maybe merge and then you can try with the published snapshot.
> [Analysis] Find primary constructor instead of assuming it's the only one

- .github/workflows/publish.yml
- build.gradle.kts
I've realized that the latest alphas were not published, it seems that it stems from a problem with the Gradle configuration. This PR fixes that problem (well, I hope, but at least now it works on my local machine).
> Fix publication workflow
